networks:
  internal:
    driver: bridge
  external:
    external: true

services:
  php:
    extends:
      file: docker-compose.yml
      service: php
    networks:
      - internal
      - external
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    ports:
      - 8080:80
    networks:
      - internal
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 3301:3306
    restart: unless-stopped
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - internal
